//! Cross-validation of `chess::simulate_move` against the reconchess Python
//! reference implementation.
//!
//! The corpus in `tests/data/rbc_corpus.json` is generated by
//! `tests/data/generate_corpus.py` running against the reconchess library;
//! see that script for the source positions and how to regenerate.
//!
//! For each entry, this test loads the FEN and the requested move (or pass),
//! runs `simulate_move`, and asserts that the resulting `taken_move` and
//! `capture_square` match the reconchess output.

use std::str::FromStr;

use chess::{simulate_move, Board, ChessMove, Square};

#[derive(serde::Deserialize, Debug)]
struct Case {
    fen: String,
    requested: Option<String>,
    taken: Option<String>,
    capture_square: Option<String>,
    #[serde(default)]
    expect_error: bool,
    #[serde(default)]
    comment: String,
}

fn load_corpus() -> Vec<Case> {
    let raw = include_str!("data/rbc_corpus.json");
    serde_json::from_str(raw).expect("rbc_corpus.json is malformed")
}

#[test]
fn matches_reconchess_reference() {
    let cases = load_corpus();
    assert!(!cases.is_empty(), "corpus is empty");

    let mut failures: Vec<String> = Vec::new();

    for c in &cases {
        let board = Board::from_str(&c.fen)
            .unwrap_or_else(|_| panic!("invalid FEN in corpus: {}", c.fen));
        let requested = c
            .requested
            .as_deref()
            .map(|m| ChessMove::from_str(m).expect("invalid UCI move in corpus"));

        let sim = simulate_move(&board, requested);
        if c.expect_error {
            if sim.is_ok() {
                failures.push(format!(
                    "case `{}`: expected Err but got Ok({:?}) for fen={} requested={:?}",
                    c.comment, sim.unwrap(), c.fen, c.requested
                ));
            }
            continue;
        }
        let result = match sim {
            Ok(r) => r,
            Err(e) => {
                failures.push(format!(
                    "case `{}`: simulate_move returned Err({:?}) for fen={} requested={:?}",
                    c.comment, e, c.fen, c.requested
                ));
                continue;
            }
        };

        let actual_taken = result.taken_move.map(|m| m.to_string());
        let actual_capture = result.capture_square.map(|s| s.to_string());

        if actual_taken != c.taken {
            failures.push(format!(
                "case `{}`: taken_move mismatch\n  fen={}\n  requested={:?}\n  expected={:?}\n  actual={:?}",
                c.comment, c.fen, c.requested, c.taken, actual_taken
            ));
        }
        if actual_capture != c.capture_square {
            failures.push(format!(
                "case `{}`: capture_square mismatch\n  fen={}\n  requested={:?}\n  expected={:?}\n  actual={:?}",
                c.comment, c.fen, c.requested, c.capture_square, actual_capture
            ));
        }

        // Also verify that the capture-square parses to a valid Square.
        if let Some(sq_str) = &c.capture_square {
            assert!(
                Square::from_str(sq_str).is_ok(),
                "corpus capture_square {} is not a valid square",
                sq_str
            );
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {} corpus case(s) failed:\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
}
